data <- read.csv("american_jobs_data.csv", header=TRUE, sep=",")

#satisfaction statistics
familyLifeSatisfaction <- table(data$q2a)
familyParty <- table(data$q2a, data$party)
t.test(data$q2a[which(data$party==1)],data$q2a[which(data$party==2)],paired=FALSE,conf.level=0.95,alternative="two.sided")
familySex <- table(data$q2a, data$sex)
t.test(data$q2a[which(data$sex==1)],data$q2a[which(data$sex==2)],paired=FALSE,conf.level=0.95,alternative="two.sided")
familyEduc <- table(data$q2a, data$educ2)
familyAge <- table(data$q2a, data$age)
cor(data$q2a, data$age, use="complete.obs")

financialLifeSatisfaction <- table(data$q2b)
financialParty <- table(data$q2b, data$party<3)
t.test(data$q2b[which(data$party==1)],data$q2b[which(data$party==2)],paired=FALSE,conf.level=0.95,alternative="two.sided")
barplot(financialParty, beside=T, main="Financial Happiness By Party", names.arg=c("Republican","Democrat"), legend.text=T, args.legend=list(x=15.45, y=24,legend=c("Very satisfied", "Somewhat satisfied", "Somewhat dissatisfied", "Very dissatisfied")))
financialSex <- table(data$q2b, data$sex)
t.test(data$q2b[which(data$sex==1)],data$q2b[which(data$sex==2)],paired=FALSE,conf.level=0.95,alternative="two.sided")
financialEduc <- table(data$q2b, data$educ2)
familyAge <- table(data$q2b, data$age)
cor(data$q2b, data$age, use="complete.obs")

workKindSatisfaction <- table(data$q2ef2)
workKindParty <- table(data$q2ef2, data$party)
t.test(data$q2ef2[which(data$party==1)],data$q2ef2[which(data$party==2)],paired=FALSE,conf.level=0.95,alternative="two.sided")
workKindSex <- table(data$q2ef2, data$sex)
t.test(data$q2ef2[which(data$sex==1)],data$q2ef2[which(data$sex==2)],paired=FALSE,conf.level=0.95,alternative="two.sided")
workKindEduc <- table(data$q2ef2, data$educ2)
familyAge <- table(data$q2ef2, data$age)
cor(data$q2ef2, data$age, use="complete.obs")

#blame statistics
jobAvailability <- table(data$q6f2)
jobAvailabilityParty <- table(data$q6f2, data$party)
t.test(data$q6f2[which(data$party==1)],data$q6f2[which(data$party==2)],paired=FALSE,conf.level=0.95,alternative="two.sided")
jobAvailabilitySex <- table(data$q6f2, data$sex)
t.test(data$q6f2[which(data$sex==1)],data$q6f2[which(data$sex==2)],paired=FALSE,conf.level=0.95,alternative="two.sided")
jobAvailabilityEduc <- table(data$q6f2, data$educ2)
familyAge <- table(data$q6f2, data$age)
cor(data$q6f2, data$age, use="complete.obs")

contractWorkerIncrease <- table(data$q7ef2)
contractWorkerParty <- table(data$q7ef2, data$party)
t.test(data$q7ef2[which(data$party==1)],data$q7ef2[which(data$party==2)],paired=FALSE,conf.level=0.95,alternative="two.sided")
contractWorkerSex <- table(data$q7ef2, data$sex)
t.test(data$q7ef2[which(data$sex==1)],data$q7ef2[which(data$sex==2)],paired=FALSE,conf.level=0.95,alternative="two.sided")
contractWorkerEduc <- table(data$q7ef2, data$educ2)
familyAge <- table(data$q7ef2, data$age)
cor(data$q7ef2, data$age, use="complete.obs")

outsourcingIncrease <- table(data$q7ff2)
contractWorkerParty <- table(data$q7ff2, data$party)
t.test(data$q7ff2[which(data$party==1)],data$q7ff2[which(data$party==2)],paired=FALSE,conf.level=0.95,alternative="two.sided")
contractWorkerSex <- table(data$q7ff2, data$sex)
t.test(data$q7ff2[which(data$sex==1)],data$q7ff2[which(data$sex==2)],paired=FALSE,conf.level=0.95,alternative="two.sided")
contractWorkerEduc <- table(data$q7ff2, data$educ2)
familyAge <- table(data$q7ff2, data$age)
cor(data$q7ff2, data$age, use="complete.obs")

techUsageIncrease <- table(data$q7gf2)
techUsageParty <- table(data$q7gf2, data$party)
t.test(data$q7gf2[which(data$party==1)],data$q7gf2[which(data$party==2)],paired=FALSE,conf.level=0.95,alternative="two.sided")
techUsageSex <- table(data$q7gf2, data$sex)
t.test(data$q7gf2[which(data$sex==1)],data$q7gf2[which(data$sex==2)],paired=FALSE,conf.level=0.95,alternative="two.sided")
techUsage <- table(data$q7gf2, data$educ2)
familyAge <- table(data$q7gf2, data$age)
cor(data$q7gf2, data$age, use="complete.obs")

usExportIncrease <- table(data$q7hf2)
usExportParty <- table(data$q7hf2, data$party)
t.test(data$q7hf2[which(data$party==1)],data$q7hf2[which(data$party==2)],paired=FALSE,conf.level=0.95,alternative="two.sided")
usExportSex <- table(data$q7hf2, data$sex)
t.test(data$q7hf2[which(data$sex==1)],data$q7hf2[which(data$sex==2)],paired=FALSE,conf.level=0.95,alternative="two.sided")
usExportEduc <- table(data$q7hf2, data$educ2)
familyAge <- table(data$q7hf2, data$age)
cor(data$q7hf2, data$age, use="complete.obs")

#responsibility statistics
governmentResponsibility <- table(data$q8df2)
governmentResponsibilityParty <- table(data$q8df2, data$party<3)
t.test(data$q8df2[which(data$party==1)],data$q8df2[which(data$party==2)],paired=FALSE,conf.level=0.95,alternative="two.sided")
barplot(governmentResponsibilityParty, beside=T, main="Attribution of Government Responsibility by Party", names.arg=c("Republican","Democrat"), legend.text=T, args.legend=list(x=12.5, y=22,legend=c("A lot", "Some", "Only a little", "None")))
governmentResponsibilitySex <- table(data$q8df2, data$sex)
t.test(data$q8df2[which(data$sex==1)],data$q8df2[which(data$sex==2)],paired=FALSE,conf.level=0.95,alternative="two.sided")
governmentResponsibilityEduc <- table(data$q8df2, data$educ2)
familyAge <- table(data$q8df2, data$age)
cor(data$q8df2, data$age, use="complete.obs")

employerResponsibility <- table(data$q8ef2)
employerResponsibilityParty <- table(data$q8ef2, data$party)
t.test(data$q2ef2[which(data$party==1)],data$q2ef2[which(data$party==2)],paired=FALSE,conf.level=0.95,alternative="two.sided")
employerResponsibilitySex <- table(data$q8ef2, data$sex)
t.test(data$q2ef2[which(data$sex==1)],data$q2ef2[which(data$sex==2)],paired=FALSE,conf.level=0.95,alternative="two.sided")
employerResponsibilityEduc <- table(data$q8ef2, data$educ2)
familyAge <- table(data$q2ef2, data$age)
cor(data$q2ef2, data$age, use="complete.obs")

collegeResponsibility <- table(data$q8ff2)
collegeResponsibilityParty <- table(data$q8ff2, data$party<3)
t.test(data$q8ff2[which(data$party==1)],data$q8ff2[which(data$party==2)],paired=FALSE,conf.level=0.95,alternative="two.sided")
barplot(governmentResponsibilityParty, beside=T, main="Attribution of College Responsibility by Party", names.arg=c("Republican","Democrat"), legend.text=T, args.legend=list(x=13, y=20,legend=c("A lot", "Some", "Only a little", "None")))
collegeResponsibilitySex <- table(data$q8ff2, data$sex)
t.test(data$q8ff2[which(data$sex==1)],data$q8ff2[which(data$sex==2)],paired=FALSE,conf.level=0.95,alternative="two.sided")
collegeResponsibilityEduc <- table(data$q8ff2, data$educ2)
familyAge <- table(data$q8ff2, data$age)
cor(data$q8ff2, data$age, use="complete.obs")

#education statistics
fourYearPreparation <- table(data$q11fa)
fourYearPrepParty <- table(data$q11fa, data$party)
t.test(data$q11fa[which(data$party==1)],data$q11fa[which(data$party==2)],paired=FALSE,conf.level=0.95,alternative="two.sided")
fourYearPrepSex <- table(data$q11fa, data$sex)
t.test(data$q11fa[which(data$sex==1)],data$q11fa[which(data$sex==2)],paired=FALSE,conf.level=0.95,alternative="two.sided")
fourYearPrepEduc <- table(data$q11fa, data$educ2)
familyAge <- table(data$q11fa, data$age)
cor(data$q11fa, data$age, use="complete.obs")

twoYearPreparation <- table(data$q12fb)
twoYearPrepParty <- table(data$q12fb, data$party)
t.test(data$q12fb[which(data$party==1)],data$q12fb[which(data$party==2)],paired=FALSE,conf.level=0.95,alternative="two.sided")
twoYearPrepSex <- table(data$q12fb, data$sex)
t.test(data$q12fb[which(data$sex==1)],data$q12fb[which(data$sex==2)],paired=FALSE,conf.level=0.95,alternative="two.sided")
twoYearPrepEduc <- table(data$q12fb, data$educ2)
familyAge <- table(data$q12fb, data$age)
cor(data$q12fb, data$age, use="complete.obs")

profSchoolPreparation <- table(data$q13fc)
profSchoolPrepParty <- table(data$q13fc, data$party)
t.test(data$q13fc[which(data$party==1)],data$q13fc[which(data$party==2)],paired=FALSE,conf.level=0.95,alternative="two.sided")
profSchoolPrepSex <- table(data$q13fc, data$sex)
t.test(data$q13fc[which(data$sex==1)],data$q13fc[which(data$sex==2)],paired=FALSE,conf.level=0.95,alternative="two.sided")
profSchoolPrepEduc <- table(data$q13fc, data$educ2)
familyAge <- table(data$q13fc, data$age)
cor(data$q13fc, data$age, use="complete.obs")

#descriptive statistics
politicalParty <- table(data$party)
politicalParty
education <- table(data$educ2)
education
sex <- table(data$sex)
sex