data <- read.csv("american_jobs_data.csv", header=TRUE, sep=",")

#satisfaction statistics
familyLifeSatisfaction <- table(data$q2a)
familyParty <- table(data$q2a, data$party)
cor(data$q2a, data$party, use="complete.obs")
familySex <- table(data$q2a, data$sex)
cor(data$q2a, data$sex, use="complete.obs")
familyEduc <- table(data$q2a, data$educ2)
cor(data$q2a, data$educ2, use="complete.obs")
#barplot(familyLifeSatisfaction, main="Satisfaction with family life", names.arg=c("Very satisfied", "Somewhat satisfied", "Somewhat dissatisfied"))

financialLifeSatisfaction <- table(data$q2b)
financialParty <- table(data$q2b, data$party)
cor(data$q2b, data$party, use="complete.obs")
financialSex <- table(data$q2b, data$sex)
cor(data$q2b, data$sex, use="complete.obs")
financialEduc <- table(data$q2b, data$educ2)
cor(data$q2b, data$educ2, use="complete.obs")

workKindSatisfaction <- table(data$q2ef2)
workKindParty <- table(data$q2ef2, data$party)
cor(data$q2ef2, data$party, use="complete.obs")
workKindSex <- table(data$q2ef2, data$sex)
cor(data$q2ef2, data$sex, use="complete.obs")
workKindEduc <- table(data$q2ef2, data$educ2)
cor(data$q2ef2, data$educ2, use="complete.obs")

#blame statistics
jobAvailability <- table(data$q6f2)
jobAvailabilityParty <- table(data$q6f2, data$party)
cor(data$q6f2, data$party, use="complete.obs")
jobAvailabilitySex <- table(data$q6f2, data$sex)
cor(data$q6f2, data$sex, use="complete.obs")
jobAvailabilityEduc <- table(data$q6f2, data$educ2)
cor(data$q6f2, data$educ2, use="complete.obs")

contractWorkerIncrease <- table(data$q7ef2)
contractWorkerParty <- table(data$q7ef2, data$party)
cor(data$q7ef2, data$party, use="complete.obs")
contractWorkerSex <- table(data$q7ef2, data$sex)
cor(data$q7ef2, data$sex, use="complete.obs")
contractWorkerEduc <- table(data$q7ef2, data$educ2)
cor(data$q7ef2, data$educ2, use="complete.obs")

outsourcingIncrease <- table(data$q7ff2)
contractWorkerParty <- table(data$q7ff2, data$party)
cor(data$q7ff2, data$party, use="complete.obs")
contractWorkerSex <- table(data$q7ff2, data$sex)
cor(data$q7ff2, data$sex, use="complete.obs")
contractWorkerEduc <- table(data$q7ff2, data$educ2)
cor(data$q7ff2, data$educ2, use="complete.obs")

techUsageIncrease <- table(data$q7gf2)
techUsageParty <- table(data$q7gf2, data$party)
cor(data$q7gf2, data$party, use="complete.obs")
techUsageSex <- table(data$q7gf2, data$sex)
cor(data$q7gf2, data$sex, use="complete.obs")
techUsage <- table(data$q7gf2, data$educ2)
cor(data$q7gf2, data$educ2, use="complete.obs")

usExportIncrease <- table(data$q7hf2)
usExportParty <- table(data$q7hf2, data$party)
cor(data$q7hf2, data$party, use="complete.obs")
usExportSex <- table(data$q7hf2, data$sex)
cor(data$q7hf2, data$sex, use="complete.obs")
usExportEduc <- table(data$q7hf2, data$educ2)
cor(data$q7hf2, data$educ2, use="complete.obs")

#responsibility statistics
governmentResponsibility <- table(data$q8df2)
governmentResponsibilityParty <- table(data$q8df2, data$party)
cor(data$q8df2, data$party, use="complete.obs")
governmentResponsibilitySex <- table(data$q8df2, data$sex)
cor(data$q8df2, data$sex, use="complete.obs")
governmentResponsibilityEduc <- table(data$q8df2, data$educ2)
cor(data$q8df2, data$educ2, use="complete.obs")

employerResponsibility <- table(data$q8ef2)
employerResponsibilityParty <- table(data$q8ef2, data$party)
cor(data$q2ef2, data$party, use="complete.obs")
employerResponsibilitySex <- table(data$q8ef2, data$sex)
cor(data$q2ef2, data$sex, use="complete.obs")
employerResponsibilityEduc <- table(data$q8ef2, data$educ2)
cor(data$q8ef2, data$educ2, use="complete.obs")

collegeResponsibility <- table(data$q8ff2)
collegeResponsibilityParty <- table(data$q8ff2, data$party)
cor(data$q8ff2, data$party, use="complete.obs")
collegeResponsibilitySex <- table(data$q8ff2, data$sex)
cor(data$q8ff2, data$sex, use="complete.obs")
collegeResponsibilityEduc <- table(data$q8ff2, data$educ2)
cor(data$q8ff2, data$educ2, use="complete.obs")

#education statistics
fourYearPreparation <- table(data$q11fa)
fourYearPrepParty <- table(data$q11fa, data$party)
cor(data$q11fa, data$party, use="complete.obs")
fourYearPrepSex <- table(data$q11fa, data$sex)
cor(data$q11fa, data$sex, use="complete.obs")
fourYearPrepEduc <- table(data$q11fa, data$educ2)
cor(data$q11fa, data$educ2, use="complete.obs")

twoYearPreparation <- table(data$q12fb)
twoYearPrepParty <- table(data$q12fb, data$party)
cor(data$q12fb, data$party, use="complete.obs")
twoYearPrepSex <- table(data$q12fb, data$sex)
cor(data$q12fb, data$sex, use="complete.obs")
twoYearPrepEduc <- table(data$q12fb, data$educ2)
cor(data$q12fb, data$educ2, use="complete.obs")

profSchoolPreparation <- table(data$q13fc)
profSchoolPrepParty <- table(data$q13fc, data$party)
cor(data$q13fc, data$party, use="complete.obs")
profSchoolPrepSex <- table(data$q13fc, data$sex)
cor(data$q13fc, data$sex, use="complete.obs")
profSchoolPrepEduc <- table(data$q13fc, data$educ2)
cor(data$q13fc, data$educ2, use="complete.obs")

#descriptive statistics
politicalParty <- table(data$party)
ideology <- table(data$ideo)
sex <- table(data$sex)

